In [ ]:
## Create model class
import torch
import torch.nn as nn

In [30]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [31]:
features = torch.randn(10, 5)  # Example input with 10 samples and 5 features
model = Model(features.shape[1])

model(features)

tensor([[0.6730],
        [0.5838],
        [0.5801],
        [0.5354],
        [0.6989],
        [0.6804],
        [0.4536],
        [0.5632],
        [0.6054],
        [0.4803]], grad_fn=<SigmoidBackward0>)

In [32]:
model.linear.weight

Parameter containing:
tensor([[-0.0500,  0.0724, -0.3871, -0.2319,  0.0177]], requires_grad=True)

In [33]:
from torchinfo  import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Another NN model

In [ ]:
# 5 input features, 3 NN middle layer neurons, 1 output neuron. So 5*3 + 3*1 = 18 parameters(Weight) in total.
#  Also 3 parameters for bias in the middle layer and 1 parameter for bias in the output layer. 
# So total parameters are 18 + 3 + 1 = 22 parameters.

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [ ]:
features = torch.randn(10, 5)  # Example input with 10 samples and 5 features
model = Model(features.shape[1])
model(features)

tensor([[0.4893],
        [0.4753],
        [0.4374],
        [0.4660],
        [0.3558],
        [0.4758],
        [0.4924],
        [0.4091],
        [0.3815],
        [0.4321]], grad_fn=<SigmoidBackward0>)

In [36]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Improvement

In [37]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
    
    def forward(self, features):
        out = self.network(features)

        return out

In [38]:
features = torch.randn(10, 5)  # Example input with 10 samples and 5 features
model = Model(features.shape[1])
model(features)

tensor([[0.4159],
        [0.5435],
        [0.4788],
        [0.4586],
        [0.4974],
        [0.4734],
        [0.4770],
        [0.5052],
        [0.4793],
        [0.5366]], grad_fn=<SigmoidBackward0>)